Moved WatchManager.js from WatchKeeper
razee-io/Kubernetes-util pull request #283
Opened 2022-09-15 17:30 UTC by nathanholzworth

Moved WatchManager.js from WatchKeeper to Kubernetes-utils to make it available to other razee projects and updated it slightly to reflect its new location.

2022-09-16 14:42 UTC, adamkingit requested changes
You'll need to add the new function to the exports to use it outside the kubernetes-util package

2022-09-28 14:15 UTC, adamkingit commented on lib/WatchManager.js
> + * Copyright 2019 IBM Corp. All Rights Reserved.
```suggestion
 * Copyright 2019, 2022 IBM Corp. All Rights Reserved.
```

2022-09-28 14:18 UTC, adamkingit requested changes
Suggest changing `let` to `const` wherever possible, and replacing all uses of `var` with `let` or `const` as appropriate

2022-09-28 14:23 UTC, nathanholzworth commented on lib/WatchManager.js
> + * Copyright 2019 IBM Corp. All Rights Reserved.
Should I do this for the index.js too?

2022-10-12 18:07 UTC, adamkingit approved these changes

2022-10-12 18:13 UTC, merged